### ISSUE TITLE
Add support for multiple URLs on an action

### ISSUE THREAD

**Issue by VasylSulakov** [microsoft/OpenAPI.NET.CSharpAnnotations#123]
Hi,
imagine an action declared as follows e.g. for, say, backward compatibility

```
/// <verb>GET</verb>
/// <url>http://server/</url>
/// <url>http://server/MeToo</url>
[Route("")]
[Route("MeToo")]
public HttpResponseMessage Get()
```

The current implementation of OpenAPI.NET.CSharpAnnotations takes FirstOrDefaullt() from the action urls, so only the first route declared wins.

**Comment by Shwetap05** [comment]
@VasylSulakov The best api design practice to follow here would be to version your API's. So you should be able to split this API into two API's and version them and annotate them accordingly.

**Comment by rfcdejong** [comment]
Seriously, it this by design to hard-code url's in code? What if there is a CI from dev -> test -> acc -> prod... where all url's are different, or what if the destination url where our api's are are being altered in azure api gateway, not even in our control. 

Or should all possible known url's be added?

**Comment by VasylSulakov** [comment]
Yes, the <url> thing is strange, it is taken as is to the Server definition, and if later the Open API produced gets exposed to Swagger UI, that url would be used for sample requests. As for the versioning, in our case, the route is the only difference, so supporting two identical versions for this reason is ridiculous. Yes, it's not ideal, but it's real life. 

Another issue is that two different POSTs under one path do not get picked up, the last one wins. E.g. /SomeResource has Post() and Post(string someData).

**Comment by rfcdejong** [comment]
For now I will skip OpenAPI.NET and OpenAPI.NET.CSharpAnnotations, it is too much in preview and the way it is going with having every comment on a method with url and verb it feels like a step back into time. Why do we have HttpGet, HttpPost attributes in code and attributes like ProducesResponseType if they have to be duplicated into comments as well..

We were using swashbuckle, but it doesn't support OAS 3.0 yet, so next step was to find another generator.. maybe NSwag is better :)

Sorry microsoft... skipping this

**Comment by VasylSulakov** [comment]
Agree, started with swashbuckle, then decided to try OpenAPI.NET+CSharpAnnotations in favor of OAS 3.0 and existing xml comments coverage, given that swashbuckle is not supported anymore for plain Web API and has issues of its own. But yes, this thing needs time to get mature.

**Comment by EricAtMSFT** [comment]
Thanks for your input on this new component. Keep in mind the goal for this repo is to harvest API contract data entirely from C# comments. Why? This guarantees that this component works on ALL C# platforms, not just Web API. By annotating your code with these comments, it doesn’t matter if your service is built on on WCF or Web API or any OWIN stack, the same OAI output is created. Proper controller comments can be standard across all these platforms.

@rfcdejong , You don’t need to document all of your URL’s in code if you don’t want to. The resulting object (OpenAPI.NET document) this component creates can be modified by your CI to add/remove new hosts. You can just document one url(localhost or INT or DEV or TEST ) and once the document is generated you should be able to add/remove/update urls from the object accordingly further down in your own pipeline.

**Comment by Shwetap05** [comment]
@VasylSulakov yes sorry realized versioning would not work here, I will discuss with the team about proposed solution here. 
And for another issue can you please provide more details so i can log a separate issue for it and which will help root cause the problem? 

Did you mean you have something like the below?

///<url>/SomeResource <url>
T Post()

And another Post like below where someData is request body?  Have you documented the request body as suggested in  https://github.com/Microsoft/OpenAPI.NET.CSharpAnnotations/wiki/C%23-Comment-Samples 

///<url>/SomeResource <url>
T Post(string someData).

**Comment by VasylSulakov** [comment]
@Shwetap05 
hi, my setup is as follows:

/// <verb>POST</verb>
/// <url>http://server/SomePath/{id:guid}</url>
/// <param name="id" cref="Guid" required="true" in="path">
/// Some id
/// </param>
/// <param name="someParameters" required="true" in="body"><see cref="string"/>
/// Some required parameters as json
/// </param>
/// <param name="optionalBoolFlag" required="false" in="body"><see cref="bool"/>
/// An optional bool flag 
/// </param>
[Route("{id:guid}")]
T Post(Guid id)

/// <verb>POST</verb>
/// <url>http://server/SomePath</url>
/// <param name="SomeData" cref="Uri" required="true" in="query">
/// Some URI data
/// </param>
/// <param name="someParameters" required="true" in="body"><see cref="string"/>
/// Some required parameters as json
/// </param>
/// <param name="optionalBoolFlag" required="false" in="body"><see cref="bool"/>
/// An optional bool flag 
/// </param>
[Route("")]
T Post(string SomeData)

We do not rely on concrete type here (and maybe that's the reason), so, the expected body request for both actions is smth like "{ "someParameters": {"data1": "value1", "data2": "value2", ...}, "optionalBoolFlag": "true", [other optional parameters may go here]}"

As a result, only the T Post(string SomeData) wins.

**Comment by Shwetap05** [comment]
@Shwetap05 many improvements have been made to the library recently, so please update to latest and reopen if issue is not fixed.
