### ISSUE TITLE
Is this going to be C# only? Or is it going to be for any .NET Language?

### ISSUE THREAD

**Issue by paulomorgado** [Microsoft/OpenAPI.NET.CSharpAnnotations#131]
Thw whole naming seems to be built aroind C#.

If you look at [NJsonSchema](https://github.com/RSuter/NJsonSchema) and [NSwag](https://github.com/RSuter/NSwag), you'll see that the naming is built around **JsonSchema** and **Swagger** with specializations for **C#** and **TypeScript**. There's no **Visual Basic** or **F#**, but it's easy to see where to plug it.

**Comment by Shwetap05** [comment]
It is for annotation xml generated by Visual Studio when you add comments in C# Classes. Regarding naming, since its a tooling built for  https://github.com/Microsoft/OpenAPI.NET, hence the naming like that.

**Comment by paulomorgado** [comment]
But I can generate that XML from Visual Basic XML documentation comments. Can´t I?

**Comment by PerthCharern** [comment]
Thanks for the question @paulomorgado.

I would believe you can, as long as the generated XML file contains the same tags and information.

That said, while we were building this library, we focused on making it for C# code base. As such, we provided the documentation wiki based on the syntax of the comments in C# (with /// marking the comments), and we only did testing with the XML files generated from C# code. 

We don't have plans to expand official support for comments in code base in other languages at the moment. The genericity of the naming, though, is a valid issue, and probably something we will look into now.

**Comment by PerthCharern** [comment]
Another complicated issue is the reflection for types. We reflect into the type specified in the annotations to build the schema registry - and as a part of that process, we also look at the Newtonsoft JsonPropertyAttribute. I'm not sure how these aspects of C# fare in the other .NET languages.

These unknown factors mean that for now, we will be focusing on C#. Consequently, the naming will revolve around C# to indicate our official support. If the naming is generic but the logic itself is not, it gives the wrong impression of what the library can do - which might be a more serious problem.

**Comment by paulomorgado** [comment]
@PerthCharern, you are aware that you don't reflect into C# types but .NET types. And those can be Visual Basic or F# also.

**Comment by PerthCharern** [comment]
Yes, I'm aware of the .NET CLR. But as I said, because we have not tested this with other languages, I'm not sure how aspects like Newtonsoft attributes will work or whether there's any difference in commenting about types in other languages. Some of these will probably work naturally like you were saying, but I can't say that with 100% confidence.

**Comment by Shwetap05** [comment]
I will close this issue. If you have more questions/concerns, feel free to reopen.
