### ISSUE TITLE
readOnly set incorrectly for model properties that only have a get

### ISSUE THREAD

**Issue by linelson** [Microsoft/OpenAPI.NET.CSharpAnnotations#136]
In the open api spec, "readOnly" has a different meaning than the way it is handled in this library.
When using reflection, model properties with only a getter and no setter are incorrectly given the "readonly" attribute. 
A property only having a "get" in a C# model does not imply that it should not be sent as part of a request body.

In the spec, "readOnly" is defined in the following way:

Relevant only for Schema "properties" definitions. Declares the property as "read only". This means that it MAY be sent as part of a response but SHOULD NOT be sent as part of the request. If the property is marked as readOnly being true and is in the required list, the required will take effect on the response only. A property MUST NOT be marked as both readOnly and writeOnly being true. Default value is false.

**Comment by Shwetap05** [comment]
Fixed.
