### ISSUE TITLE
How do you add a "securityDefinitions" section?

### ISSUE THREAD

**Issue by TobyHaddon** [Microsoft/OpenAPI.NET.CSharpAnnotations#143]
{
  "swagger": "2.0",
  "host": "functionappserverlesstry3.azurewebsites.net",
  "basePath": "/",
  "paths": {
   ...
   }
   ....

   "securityDefinitions": {
    "apikeyQuery": {
      "type": "apiKey",
      "name": "code",
      "in": "query"
    }
  }
}

**Comment by Shwetap05** [comment]
Will need to add support for it currently library do not have a proposed tag to document SecurityDefinitions.

**Comment by Shwetap05** [comment]
This is supported now.

**Comment by JeanLucHofer** [comment]
Thanks - what annotations do you need to use in the code to activate it?

**Comment by Shwetap05** [comment]
@JeanLucHofer you can use <security> tag and more details and examples for it can be found in https://github.com/Microsoft/OpenAPI.NET.CSharpAnnotations/wiki/C%23-Comment-Tag-Guide

**Comment by JeanLucHofer** [comment]
Thanks Shweta - any chance you could add a 4th example for apiKey in the guide?

**Comment by Shwetap05** [comment]
@JeanLucHofer yes realized i missed it so added it also this page have it too https://github.com/Microsoft/OpenAPI.NET.CSharpAnnotations/wiki/C%23-Comment-Samples

**Comment by TobyHaddon** [comment]
Works well - thank you
