### ISSUE TITLE
Add support for populating a document level description (Info.Description field)

### ISSUE THREAD

**Issue by scott-lin** [Microsoft/OpenAPI.NET.CSharpAnnotations#147]
In order to do this today, we have to inject the description string into the document model after it has been output from the C# Annotations library. It would be convenient if the library handled this for customers. Especially in the case where variants are produced and multiple assignments for this field must be performed.

**Comment by PerthCharern** [comment]
The document config section in the Config file seems like the right place for this.

**Comment by Shwetap05** [comment]
Yes agree with perth.

**Comment by Shwetap05** [comment]
But if we need to support markdown files then document config section can't be used, instead we can use OpenApiDocumentGenerationSettings

**Comment by Shwetap05** [comment]
Work is done.
