### ISSUE TITLE
Parse parameters affected by the name munging in Roslyn (those with hyphens in the name)

### ISSUE THREAD

**Issue by jl-g** [Microsoft/OpenAPI.NET.CSharpAnnotations#148]
As seen in [this Roslyn issue](https://github.com/dotnet/roslyn/issues/26292), Roslyn doesn't support parameter names with hyphens in them. For example, adding a parameter for 'Content-Type' results in a param tag of 'Content-Type-Type' in the XML annotation file. 
Given that getting Roslyn to support this scenario might be difficult, we should consider having the CSharpAnnotation reader expect that duplication in the name. In the above example, it would know to interpret 'Content-Type-Type' as 'Content-Type'. We might also want to pass an optional argument to the config object to override this behavior.

**Comment by Shwetap05** [comment]
Fix available in Microsoft.OpenApi.CSharpAnnotations.DocumentGeneration.1.0.0-beta048.nupkg
