### ISSUE TITLE
Setting the content type to "application/x-www-form-urlencoded" or "multipart/form-data"

### ISSUE THREAD

**Issue by andrewliang** [Microsoft/OpenAPI.NET.CSharpAnnotations#159]
Is there a way to set the content type to "application/x-www-form-urlencoded" or "multipart/form-data"?
It seems to be supported in OpenAPI.NET's object model (eg:  https://github.com/Microsoft/OpenAPI.NET/blob/d79395555eaf5ff8815d6477d681e43015c427d1/test/Microsoft.OpenApi.Readers.Tests/V2Tests/OpenApiPathItemTests.cs)

P.S. Thank you guys for this repo and your hard work!

**Comment by Shwetap05** [comment]
Yes, you should be able to use attribute type = "application/x-www-form-urlencoded" e.g below

<param name="sampleObject" in="body" type="application/x-www-form-urlencoded"><see cref="SampleObject1"/>Sample object</param>

**Comment by andrewliang** [comment]
Thanks @Shwetap05. This sample comment works when I generate a v3 OAS document using the `OpenApiSpecVersion.OpenApi3_0` setting. However, when generating a v2 OAS document, the properties of the `SampleObject1` do not showing up in the spec file.

**Comment by Shwetap05** [comment]
@andrewliang Are you converting to V2 document using Microsoft.OpenApi.Readers? If so it could be a bug in OpenApi.Net so can you please open an issue for it on https://github.com/Microsoft/OpenAPI.NET?

**Comment by andrewliang** [comment]
hm.. I'm not using `Microsoft.OpenApi.Readers` directly in my code but is it possible that `Microsoft.OpenApi.CSharpAnnotations.DocumentGeneration.OpenApiGenerator` is using it? 
I'm using the generator to read the dll and xml files as instructed in the `README.md` file. I'm also calling the OpenApiDocument.Serialize() method and passing in `OpenApiSpecVersion.OpenApi2_0`

**Comment by Shwetap05** [comment]
@andrewliang Microsoft.OpenApi.CSharpAnnotations.DocumentGeneration.OpenApiGenerator does not own any serialization code, OpenApiDocument.Serialize()  is owned by https://github.com/Microsoft/OpenAPI.NET so can you please open an issue with details on that repo?

**Comment by andrewliang** [comment]
No problem. I'll open an issue against https://github.com/Microsoft/OpenAPI.NET.

Thanks again.
