### ISSUE TITLE
Array types are illegal for response

### ISSUE THREAD

**Issue by VasylSulakov** [Microsoft/OpenAPI.NET.CSharpAnnotations#162]
I'm not able to provide return type of byte array for a response
`<response code="200"><see cref="T:byte[]"/></response>`

**Comment by Shwetap05** [comment]
@VasylSulakov .Net documentation doesn't provide a cleaner way to document arrays and compiler also doesn't compile the /// comments with array into a fully qualified type name. So you will need to document the array type like below

<response code="200"><see cref="T:System.Byte[]"/></response>

**Comment by Shwetap05** [comment]
I will be closing this please reopen if you have more questions.
