### ISSUE TITLE
Support for System.Runtime.Serialization - DataContract and DataMember annotations

### ISSUE THREAD

**Issue by dralpus** [microsoft/OpenAPI.NET.CSharpAnnotations#195]
For some core data model packages, we don't want to take an external dependency on NewtonSoft. Therefore, we are using built-in System.Runtime.Serialization and its annotations to define the DataContract and DataMembers. We need to have support on following features:
1. Renaming property names using [DataMember(Name = TitlePropertyName)] annotation.
2. If a class has [DataContract] annotation, and if 1 of the property contains [DataMember] annotation, only show the properties if they have [DataMember] annotation.
3. (Optional) support for [IgnoreDataMember] annotation. If no properties in the class have [DataMember] annotation, by default all should be DataMembers, except the ones which are marked with [IgnoreDataMember] annotation.

**Comment by Shwetap05** [comment]
Closing this as issues is fixed. Please reopen if it isn't.
