### ISSUE TITLE
Support parameters that contains dollar sign $

### ISSUE THREAD

**Issue by dralpus** [Microsoft/OpenAPI.NET.CSharpAnnotations#197]
Some query parameters start with `$` sign, for example: `$skip` but swagger documentation shows them as `$skip$skip` (I can see VSBuild xml translates into `$skip$skip` but the naming annotation is actually `$skip`).

Could you please show the parameter names as the same what is written?

**Comment by Shwetap05** [comment]
Fix available in Microsoft.OpenApi.CSharpAnnotations.DocumentGeneration.1.0.0-beta048.nupkg
