### ISSUE TITLE
Question: should I write code to generate OpenAPI doc?

### ISSUE THREAD

**Issue by tonglingchen** [Microsoft/OpenAPI.NET.CSharpAnnotations#203]
In the sample code section(https://github.com/Microsoft/OpenAPI.NET.CSharpAnnotations#simple-example-code) there is code sample to actually generate OpenAPI doc. I am confused - do I need to do this in my project? Or the build task will take care of it. 

Also, if I am not able to use build task, is there an exe (or powershell script) I can use to generate OpenAPI doc?

**Comment by Shwetap05** [comment]
@tonglingchen if you use build task, it calls the library so you just need to setup the build task with required input and it should take care of generating the document.

There is no exe available but should be easy to write your own leveraging the nuget package of the library and you should be able to get information around how to call the library from the Readme. Let me know if you have any specific question on calling the library and i can help.

**Comment by Shwetap05** [comment]
@tonglingchen  closing this issue as have provided the answer, please reopen if you have any specific question on writing the exe to call the library.
