### ISSUE TITLE
Add suggestion to enable XML documentation file for all configurations

### ISSUE THREAD

**Issue by JeffreyCA** [microsoft/OpenAPI.NET.CSharpAnnotations#204]
I mistakenly enabled it only for the Debug configuration so when the Azure Pipelines task ran it could not find the .xml file since it built the Release configuration.

**Comment by Shwetap05** [comment]
@JeffreyCA Setting the output xml file is done at the csproj level, so this is not something that can be done with DevOps task. And do this you should right click your csproj --> Build --> Set Configuration to Release --> Check Xml Documentation Path under Output.

**Comment by JeffreyCA** [comment]
Yes that is what I ended up doing. I just wanted to suggest adding this tip as part of the README.

**Comment by EricAtMSFT** [comment]
Hey Jeffrey,
Glad you got it working.
In the Readme under mechanics there's a specific screenshot instructing folks to check the "XML Documentation" checkbox.

Cheers

/Eric
