### ISSUE TITLE
Documentation missing how to specify optional paramaters

### ISSUE THREAD

**Issue by MadocGwyn** [microsoft/OpenAPI.NET.CSharpAnnotations#209]
I see in the old issues you can use JSON.NET decorations to specify if members in models are required but what about parameters into the functions? Right now everything's coming out required=true in the generated document.

**Comment by Shwetap05** [comment]
@MadocGwyn so path parameter required is set by default. For other parameter tag like query, header, if required attribute like below is not specified it should be false.

```xml<param name="samplePathParam1" cref="float" in="path" required="false">Path param 1</param>```

Does this help?

**Comment by MadocGwyn** [comment]
That looks like exactly what I need. I just didn't see it in the documentation. Thanx!

**Comment by Shwetap05** [comment]
@MadocGwyn sorry about that, looks like we missed to document it, I will update the document. Also closing the issue, please reopen if you have more question around the same.

**Comment by MadocGwyn** [comment]
Ok, so that sort of works how I would expect. 
It makes it to the xml. 
![image](https://user-images.githubusercontent.com/8175794/57736433-ea8ef780-7675-11e9-9a8b-4781d578d0a3.png)
But not to the generated document

![image](https://user-images.githubusercontent.com/8175794/57736551-6c7f2080-7676-11e9-9c8b-3a6e997458f6.png)


Error count is 0 in the GenerationDiagnostic.

Now I'm wondering if this is a side effect of my weird use case where the argument is in my route, but NOT an argument to the actual function. It is read by a custom filter that does the needful.

**Comment by swettstein** [comment]
i'm running into the same problem. i have an optional route parameter but path parameters are always set to required even if i add `required="false"` to the param tag.

**Comment by EricAtMSFT** [comment]
@swettstein  We deliberately made path params required. I would argue it's a best practice to move optional params to querystring if possible.

**Comment by MadocGwyn** [comment]
@EricAtMSFT  So your breaking your standard (reading the settings from the xml)
To enforce your standard/arbitrary best practice.
You should then update your documentation to say that to use your tool our api's have to comply with your best practices. I thought the point of this tool was documention not enforcing your practices.

**Comment by swettstein** [comment]
to make something unable to be overriden is not "best practice". you've made it the "only practice". why not set the default required value for path params to true unless overridden? if the default value for query params is false unless overridden, why can't default for path params be true unless overridden?

**Comment by MadocGwyn** [comment]
I checked to be sure and most best practices involve using optional arguments.
Here is an example from the first google hit on REST best practices.

GET /cars/711/drivers/ Returns a list of drivers for car 711
GET /cars/711/drivers/4 Returns driver #4 for car 711

**Comment by Shwetap05** [comment]
@MadocGwyn The library follows the open api specification https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#parameterObject

Which states below

Determines whether this parameter is mandatory. If the parameter location is "path", this property is REQUIRED and its value MUST be true. Otherwise, the property MAY be included and its default value is false.

**Comment by EricAtMSFT** [comment]
Let's be clear. This repo was built originally for some of our "internal" tooling and like many good things at Microsoft, we decided to share it. You're welcome to make a case for any changes you see fit, PR's are, of course, welcome.

**Comment by MadocGwyn** [comment]
Actually, objection withdrawn. The OpenAPI spec does in fact say that. I will just continue to use my patched one and understand that it is not OpenAPI compliant. The consumers we're using deal with it fine so that's not a concern. I won't submit a PR on something that would break the spec.

**Comment by MadocGwyn** [comment]
Thinking about this more I don't like the idea of just abandoning the spec. In our API's there is only ever one optional parameter and it is the last one. I guess the "RightWay" to fix this and keep compliance would be to fix is to that if it hits one with an optional parameter, it puts in TWO entries. One without the optional parameter(like omitting it completely), and one with, with the required=true .
