### ISSUE TITLE
Custom Class Annotations

### ISSUE THREAD

**Issue by jdusome** [microsoft/OpenAPI.NET.CSharpAnnotations#223]
Hello,

Is it possible to add custom annotations to properties within an object? There are a few Microsoft specific properties I need to add to my Open API definition, but it appears that this library does not recognize them, or I am doing it wrong.

Here is my class:

![image](https://user-images.githubusercontent.com/22377503/65913466-f9b0e080-e39d-11e9-9782-502162f1fc46.png)

Here is the output OpenAPI JSON:

![image](https://user-images.githubusercontent.com/22377503/65913497-09c8c000-e39e-11e9-8be4-a888b725b774.png)

Ideally, the output would contain special Microsoft properties. Please let me know if this is possible.

Thank you.

**Comment by Shwetap05** [comment]
@jdusome Do you want these annotations ```<x-ms-notification-url>``` to show up as https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#specificationExtensions ? If so you can achieve that my writing a custom filter class that derives from https://github.com/microsoft/OpenAPI.NET.CSharpAnnotations/blob/master/src/Microsoft.OpenApi.CSharpAnnotations.DocumentGeneration/OperationFilters/IOperationFilter.cs 

And passing it to the libarary for an example take a look at test case GetTestCasesForPassANewFilterAndShouldReturnCorrectDocument in https://github.com/microsoft/OpenAPI.NET.CSharpAnnotations/blob/master/test/Microsoft.OpenApi.CSharpAnnotations.DocumentGeneration.Tests/OpenApiDocumentGeneratorTests/OpenApiDocumentGeneratorTest.cs

**Comment by jdusome** [comment]
I think that is precisely what I am looking for, I will give that a shot and get back to you if I have any questions regarding the custom filter. Thank you.

**Comment by jdusome** [comment]
@Shwetap05 I was able to successfully use an Operation Filter to get some of the custom Microsoft extensions into the Open API document.  Thank you very much for your response. Is it possible to do something similar for the Schemas that are generated? In my original post, I am referring to the object that is returned from an operation. The library is currently able to import the summary, although it would be really nice if I could also import additional elements as well.

**Comment by Shwetap05** [comment]
@jdusome can you please provide more details on what additional elements you want included in schema?

**Comment by jdusome** [comment]
Certainly! In the original screenshot, you can see that I created the XML style comments on my PortalUserRegistrationSubscribeRequest object. It generates the second screenshot in the Open API definition, though I would like to generate the following:

![image](https://user-images.githubusercontent.com/22377503/65988003-017f8c00-e455-11e9-851a-cec1eacfc906.png)

(Notice the custom x-ms attributes on the callBackUrl property)

I was able to accomplish this for the operations using an Operation Filter as you suggested, but I would like to accomplish something similar for the Schemas that being generated.
