### ISSUE TITLE
Add a filter for detecting and handling global serialization settings

### ISSUE THREAD

**Issue by scott-lin** [Microsoft/OpenAPI.NET.CSharpAnnotations#93]
Some services/applications set global serialization settings instead of specifying attributes on every contract class property. For applications that do this, their properties in the resulting OpenAPI Document model may have incorrect casing. One such example is our FD application.

**Comment by Shwetap05** [comment]
Fixes and user should be able to customize property name resolver via OpenAPIDocumentGenerationSettings.
