### ISSUE TITLE
Improve parameter filter messaging for "in" attribute

### ISSUE THREAD

**Issue by scott-lin** [Microsoft/OpenAPI.NET.CSharpAnnotations#97]
Given this annotation,

    /// <param name="MS-CorrelationId" cref="string" in="headerZZZ">Correlation ID for the request</param>

The error produced is,

    ExceptionType: MissingInAttributeException || Message: In attribute is missing from parameter(s): "MS-CorrelationId-CorrelationId"

There are two bugs,
1. The messaging should indicate the "in" attribute value is not supported. Ideally, it would indicate what values are supported at the same time.
2. The parameter name in the message is wrong.

**Comment by Shwetap05** [comment]
fixed.
